### PR TITLE
Add description of Controls.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by RSDuck** [comment]
can you please include that the default controls on New 3ds systems are different: https://github.com/RSDuck/craftus_reloaded/blob/master/source/entity/PlayerController.c#L41-L70

**Comment by ghost** [comment]
Oh, sorry, I have an OLD 3DS, and I thought it was the same control for the two versions.

**Comment by RSDuck** [comment]
I just had an idea. How about putting everything inside a table, so it's more compact?

Something like that:

Control(there's probably a better name for this)|Old 3ds default|New 3ds default
------------------------------------------------|----------------|-----------------
Forward|X|Circle Pad Up

**Comment by RSDuck** [comment]
ok, everything's fine. Thanks, will be merged! 👍 ✔️

**Comment by RSDuck** [comment]
upps, pressed the wrong button

**Comment by ghost** [comment]
What?

**Comment by RSDuck** [comment]
this isn't the first time, where I accidently press the Close Pull Request button instead of the Merge Pull Request one

**Pull request merged**
