### PR TITLE
Swap L&R with Y&A for a more comfy control + More

### PR DESCRIPTION
**Pull request by cohaereo**
Successfully tested with a clean copy of the latest master branch

### CODE REVIEW

**Comment by cohaereo** [comment]
ignore the first 2 commits, thats just me struggling to upload a file

**Comment by cohaereo** [comment]
-Added Wool + Bedrock
-Added Bedrock to Superflat worldgen

**Comment by RSDuck** [comment]
good additions 👍, but please, if you do another pull request(regardless whether it's Craftus or another project), keep the git history cleaner 😄

**Comment by RSDuck** [comment]
sorry pressed the wrong button

**Comment by cohaereo** [comment]
Yea i struggled a bit with the github system, and i'll be happy to contribute more to this project!

**Pull request merged**
